lb1_initial_angle: '90'
lb2_initial_angle: '45'
lb3_initial_angle: '45'
lf1_initial_angle: '90'
lf2_initial_angle: '45'
lf3_initial_angle: '45'
rb1_initial_angle: '90'
rb2_initial_angle: '135'
rb3_initial_angle: '135'
rf1_initial_angle: '90'
rf2_initial_angle: '135'
rf3_initial_angle: '135'
